### PR TITLE
Added plugins and parser as peer dependency

### LINKED ISSUE #2: ESLint Plugins and Parser not declared as Peer Dependency
If `eslint-plugin-flowtype` , `eslint-plugin-import` and `babel-eslint` are declared as peer dependency, developers will be notified to install them.

### PR DESCRIPTION
**Pull request by akshitkrnagpal**
Fixes #2

### CODE REVIEW

**Comment by saghul** [comment]
@hristoterezov any objections here?

**Review by saghul — APPROVED** [review]

**Comment by hristoterezov** [comment]
I'm wondering shouldn't we add also - eslint-plugin-jsdoc and eslint-plugin-react? But if we add them probably the projects that are using only the rules from index.js will see a warning for eslint-plugin-react for example. I'm not sure what is the best way to handle this. WDYT? Any ideas @AkshitKrNagpal ?

**Comment by hristoterezov** [comment]
I'd say it is probably still better to have them.

**Comment by akshitkrnagpal** [comment]
@hristoterezov 
Yeah. I was also wondering this and asked when we had our last video conference.
>But if we add them probably the projects that are using only the rules from index.js will see a warning for eslint-plugin-react for example.

@saghul said that we shouldn't add them because of the same reason. 

> I'd say it is probably still better to have them.

I agree with this also.

I would say lets add them. If not I guess we have another option where we all should agree.
Lets display a custom message postInstall. Please see this [link](https://stackoverflow.com/a/31875521). 
Maybe we can do something like this. @gpolitis ?

**Comment by hristoterezov** [comment]
Hmm... The problem is that on the npm install step we don't have idea how the user would the package. So we should either add nothing or either add them all.

I'm in favor of adding them all. But lets wait for @saghul to tell us his opinion!

**Comment by saghul** [comment]
In that case I'd go and not add any of them, but document this on the README we now have thanks to Akshit. WDYT?

**Comment by akshitkrnagpal** [comment]
@saghul 
I already did add which plugins to install and when in documentation. PTAL if we need any changes in that.
If we shouldn't add them as peer dependency I think we can close this.

**Comment by saghul** [comment]
True that. Thanks a ton @AkshitKrNagpal! I'm going to go ahead and close this then.

**Pull request closed without merging**
